// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type URLMessage struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *URLMessage) Reset()         { *m = URLMessage{} }
func (m *URLMessage) String() string { return proto.CompactTextString(m) }
func (*URLMessage) ProtoMessage()    {}
func (*URLMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *URLMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_URLMessage.Unmarshal(m, b)
}
func (m *URLMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_URLMessage.Marshal(b, m, deterministic)
}
func (m *URLMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_URLMessage.Merge(m, src)
}
func (m *URLMessage) XXX_Size() int {
	return xxx_messageInfo_URLMessage.Size(m)
}
func (m *URLMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_URLMessage.DiscardUnknown(m)
}

var xxx_messageInfo_URLMessage proto.InternalMessageInfo

func (m *URLMessage) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type ResponseMessage struct {
	Headers              []byte   `protobuf:"bytes,1,opt,name=headers,proto3" json:"headers,omitempty"`
	Body                 []byte   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseMessage) Reset()         { *m = ResponseMessage{} }
func (m *ResponseMessage) String() string { return proto.CompactTextString(m) }
func (*ResponseMessage) ProtoMessage()    {}
func (*ResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *ResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseMessage.Unmarshal(m, b)
}
func (m *ResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseMessage.Marshal(b, m, deterministic)
}
func (m *ResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseMessage.Merge(m, src)
}
func (m *ResponseMessage) XXX_Size() int {
	return xxx_messageInfo_ResponseMessage.Size(m)
}
func (m *ResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseMessage proto.InternalMessageInfo

func (m *ResponseMessage) GetHeaders() []byte {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *ResponseMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*URLMessage)(nil), "api.URLMessage")
	proto.RegisterType((*ResponseMessage)(nil), "api.ResponseMessage")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x92, 0xe3, 0xe2, 0x0a, 0x0d,
	0xf2, 0xf1, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x15, 0x12, 0xe0, 0x62, 0x2e, 0x2d, 0xca, 0x91,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x95, 0xec, 0xb9, 0xf8, 0x83, 0x52, 0x8b, 0x0b,
	0xf2, 0xf3, 0x8a, 0x53, 0x61, 0x8a, 0x24, 0xb8, 0xd8, 0x33, 0x52, 0x13, 0x53, 0x52, 0x8b, 0x8a,
	0xc1, 0x0a, 0x79, 0x82, 0x60, 0x5c, 0x21, 0x21, 0x2e, 0x96, 0xa4, 0xfc, 0x94, 0x4a, 0x09, 0x26,
	0xb0, 0x30, 0x98, 0x6d, 0x64, 0xc9, 0xc5, 0xec, 0x18, 0xe0, 0x29, 0x64, 0xc4, 0xc5, 0xee, 0x9c,
	0x98, 0x93, 0x13, 0x1a, 0xe4, 0x23, 0xc4, 0xaf, 0x07, 0x72, 0x03, 0xc2, 0x56, 0x29, 0x11, 0xb0,
	0x00, 0x9a, 0x35, 0x06, 0x8c, 0x49, 0x6c, 0x60, 0x77, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x26, 0xe6, 0x22, 0xe1, 0xb4, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	CallURL(ctx context.Context, in *URLMessage, opts ...grpc.CallOption) (API_CallURLClient, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) CallURL(ctx context.Context, in *URLMessage, opts ...grpc.CallOption) (API_CallURLClient, error) {
	stream, err := c.cc.NewStream(ctx, &_API_serviceDesc.Streams[0], "/api.API/CallURL", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPICallURLClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_CallURLClient interface {
	Recv() (*ResponseMessage, error)
	grpc.ClientStream
}

type aPICallURLClient struct {
	grpc.ClientStream
}

func (x *aPICallURLClient) Recv() (*ResponseMessage, error) {
	m := new(ResponseMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	CallURL(*URLMessage, API_CallURLServer) error
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) CallURL(req *URLMessage, srv API_CallURLServer) error {
	return status.Errorf(codes.Unimplemented, "method CallURL not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_CallURL_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(URLMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).CallURL(m, &aPICallURLServer{stream})
}

type API_CallURLServer interface {
	Send(*ResponseMessage) error
	grpc.ServerStream
}

type aPICallURLServer struct {
	grpc.ServerStream
}

func (x *aPICallURLServer) Send(m *ResponseMessage) error {
	return x.ServerStream.SendMsg(m)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.API",
	HandlerType: (*APIServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CallURL",
			Handler:       _API_CallURL_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
